image: node:20.12.2

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

testing:
  stage: test
  script:
    - npm run lint

pages:
  stage: deploy
  before_script:
    - rm -rf public/
  script:
    - npm run build
  after_script:
    - cp public/index.html public/404.html
    - cp public/index.html public/403.html
  artifacts:
    paths:
    - public
  only:
    - dev
